version: '3.1'

services:
  generator:
    image: 127.0.0.1:55000/gen:ci-14
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  integration:
    image: 127.0.0.1:55000/gen:integration-14
    build: .